const products = [
    {
        "id":1,
        "image":"images/1.png",
        "name" : "2017 Aegidienberger",
        "birth":"2017",
        "breed":"Aegidienberger",
        "sex":"Mare",
        "height" : "14.2hh",
        "dameSire":"Petite Nonette",
        "sire":"Oscar",
        "price":"10000",
        "age":"Young Horses",
        "discipline":"Dressage",
        "colour":"Brown",
        "country":"Albania",
        "summary":"Meet Ray, a captivating Aegidienberger blending Andalusian elegance with Icelandic resilience. Perfect for dressage, trails, or family rides, Ray excels in every role. Intelligent, agile, and trainable, Ray suits riders of all levels. Don't miss the chance to own this exceptional horse. Contact us to meet Ray today!",
        "slideOne":"images/12.png",
        "slideTwo":"images/13.png",
        "slideThree":"images/14.png",
        "cryptoPrices":{
            Bitcoin:0.150903,
            Lightning:154.94000000,
            Ethereum:3.302259,
            USDC:10000,
            Tether:10000,
            LTC:121.315,
            Doge:64641.241111
        }
    },
    {
        "id":2,
        "image":"images/2.jpg",
        "name" : "2020 Warmblood",
        "birth":"2020",
        "breed":"Warmblood",
        "sex":"Mare",
        "height" : "15hh",
        "dameSire":"Tiffany  Romellle",
        "sire":"",
        "price":"22000",
        "age":"Young Horses",
        "colour":"Black",
        "country":"Albania",
        "discipline":"Eventing",
        "summary":"Meet Aurora, a striking Warmblood with impeccable breeding and grace. Aurora boasts exceptional movement and conformation, making her a top contender in the show ring. With a gentle temperament and eager-to-please attitude, she's suitable for riders of all levels. Whether you're aiming for the podium or seeking a loving companion for leisurely rides, Aurora is the perfect partner. Contact us now to make Aurora a part of your equestrian journey!",
        "slideOne":"images/2.jpg",
        "slideTwo":"images/31.jpg",
        "slideThree":"images/32.jpg",
        "cryptoPrices":{
            Bitcoin:0.332205,
            Lightning:340.88000000,
            Ethereum:7.261205,
            USDC:22000,
            Tether:22000,
            LTC:267.0875,
            Doge:142210.730446
        }
    },
    {
        "id":3,
        "image":"images/3.jpg",
        "name" : "Black Glamourdale Filly",
        "birth":"2017",
        "breed":"Filly",
        "sex":"Stallion",
        "height" : "17hh",
        "dameSire":"Burggraaf",
        "sire":"Sire: Thuja",
        "price":"19000",
        "age":"Adults",
        "colour":"Black",
        "country":"Albania",
        "discipline":"Dressage",
        "summary":"Exceptional black Glamourdale filly out of a proven Budweiser mare who's previous foal is now a standing stallion with an elite level performance rider. Exquisite movement and confirmation. An asset to any breeding stable. Kind and gentle temperament (pleasure to do anything with). Perfect opportunity to secure a Glamourdale horse in an Olympic year. Located in the Hunter Valley. Ready to be weaned",
        "slideOne":"images/3.jpg",
        "slideTwo":"images/10.jpg",
        "slideThree":"images/11.jpg",
        "cryptoPrices":{
            Bitcoin:0.286905,
            Lightning:294.40000000,
            Ethereum:6.276903,
            USDC:19000,
            Tether:19000,
            LTC:230.5825,
            Doge:122580.645161
        }
    },
    {
        "id":4,
        "image":"images/4.jpg",
        "name" : "Competitive TB jumper",
        "birth":"2010",
        "breed":"Competitive TB jumper",
        "sex":"Gelding",
        "height" : "16.1hh",
        "dameSire":"Silver Cachelle",
        "sire":"Domesday",
        "price":"30000",
        "age":"Adults",
        "colour":"Grey",
        "country":"Albania",
        "discipline":"Eventing",
        "summary":"Meet Maximus, a top-notch jumper gelding with a heart of gold. Maximus excels in the arena, effortlessly clearing fences with power and precision. With years of experience in the jumper ring, he's a reliable partner for riders aiming for the top. His athletic build and sharp mind make him a standout in competition. Whether you're a seasoned competitor or aspiring to reach new heights, Maximus is ready to take you there. Don't miss out on the opportunity to ride to victory with Maximus. Contact us today to make him your winning teammate",
        "slideOne":"images/4.jpg",
        "slideTwo":"images/20.jpg",
        "slideThree":"images/21.jpg",
        "cryptoPrices":{
            Bitcoin:0.453074,
            Lightning:464.83000000,
            Ethereum:9.913488,
            USDC:30000,
            Tether:30000,
            LTC:363.8127,
            Doge:193548.387096
        }
    },
    {
        "id":5,
        "image":"images/5.png",
        "name" : "2017 Arabian",
        "birth":"2017",
        "breed":"Arabian",
        "sex":"Mare",
        "height" : "14.2hh",
        "dameSire":"Petite Nonette",
        "sire":"Oscar",
        "price":"12000",
        "age":"Young Horses",
        "colour":"Brown",
        "country":"Albania",
        "discipline":"Hunter/Jumper",
        "summary":"Meet Zephyr, a captivating Arabian horse boasting elegance and spirit. With a sleek coat and graceful features, Zephyr embodies the essence of the Arabian breed. Renowned for intelligence and endurance, Zephyr excels in various disciplines. Whether you seek a competitive partner or a cherished companion, Zephyr offers versatility and charm. Don't miss the chance to own this exceptional Arabian. Contact us today to discover the magic of Zephyr.",
        "slideOne":"images/35.jpg",
        "slideTwo":"images/33.jpg",
        "slideThree":"images/34.jpg",
        "cryptoPrices":{
            Bitcoin:0.181229,
            Lightning:185.93000000,
            Ethereum:3.968267,
            USDC:12000,
            Tether:12000,
            LTC:145.4192,
            Doge:77419.354838
        }
    },
    {
        "id":6,
        "image":"images/39.jpg",
        "name" : "2021 Appaloosa",
        "birth":"2021",
        "breed":"Appaloosa",
        "sex": "Gelding",
        "height" : "15.3hh",
        "dameSire":"Petite Nonette",
        "sire":"Oscar",
        "price":"15000",
        "age":"Foal",
        "colour":"Brown",
        "country":"Albania",
        "discipline":"Eventing",
        "summary":"Meet Apache, a striking Appaloosa with a gentle demeanor. With eye-catching coat patterns and a calm disposition, Apache stands out in any arena. Whether you're hitting the trails or enjoying leisurely rides, Apache's beauty and reliability shine through. Suitable for riders of all levels, Apache is ready to be your trusted companion. Contact us now to bring Apache into your equestrian world!",
        "slideOne":"images/39.jpg",
        "slideTwo":"images/40.jpg",
        "slideThree":"images/41.jpg",
        "cryptoPrices":{
            Bitcoin:0.227201,
            Lightning:232.42000000,
            Ethereum:4.9636,
            USDC:15000,
            Tether:15000,
            LTC:182.1714,
            Doge:96774.193548
        }
    },
    {
        "id":7,
        "image":"images/7.png",
        "name" : "2019 Friesian",
        "birth":"2019",
        "breed":"Freisian",
        "sex":"Stallion",
        "height" : "16.4hh",
        "dameSire":"Nonette",
        "sire":"Monttro",
        "price":"25000",
        "age":"Young Horses",
        "colour":"Black",
        "country":"Albania",
        "discipline":"Dressage",
        "summary":"Meet Midnight, a majestic Friesian with an elegant presence. With flowing mane and tail, Midnight exudes grace and power. Whether you're seeking a striking partner for dressage or a captivating mount for pleasure riding, Midnight impresses in every setting. With a gentle temperament and impressive stature, Midnight is sure to turn heads wherever he goes. Contact us now to make Midnight the crown jewel of your stable!",
        "slideOne":"images/36.jpg",
        "slideTwo":"images/37.jpeg",
        "slideThree":"images/38.jpeg",
        "cryptoPrices":{
            Bitcoin:0.378669,
            Lightning:386.58000000,
            Ethereum:8.264681,
            USDC:25000,
            Tether:25000,
            LTC:303.1405,
            Doge:161603.102779
        }
    },
{
    "id":8,
    "image":"images/8.jpg",
    "name" : "Henbury Cambridge",
    "birth":"2020",
    "breed":"Warmblood",
    "sex":"Gelding",
    "height" : "16.1hh",
    "dameSire":"Varese",
    "sire":"Cachassini",
    "price":"28000",
    "age":"Young Horses",
    "colour":"Brown",
    "country":"Albania",
    "discipline":"Show Jumping",
    "summary":"Meet Henbury Cambridge, a versatile Warmblood gelding boasting elegance and talent. With impeccable movement and a gentle nature, Cambridge shines in the arena and on leisurely rides. Whether you're aiming for the show ring or seeking a reliable companion, Cambridge excels. Don't miss out on the opportunity to ride with Henbury Cambridge—contact us today",
    "slideOne":"images/8.jpg",
    "slideTwo":"images/42.jpg",
    "slideThree":"images/43.jpg",
    "cryptoPrices":{
        Bitcoin:0.42318,
        Lightning:432.97000000,
        Ethereum:9.252803,
        USDC:28000,
        Tether:28000,
        LTC:339.4762,
        Doge:180995.475113
    }
},   
{
    "id":9,
    "image":"images/9.jpg",
    "name" : "2017 Pony",
    "birth":"2017",
    "breed":"Pony",
    "sex":"Gelding",
    "height" : "13.2hh",
    "dameSire":"Oak",
    "sire":"Rocky",
    "price":"30000",
    "age":"Young Horses",
    "colour":"Chestnut",
    "country":"Albania",
    "discipline":"Show Jumping",
    "summary":"Meet Pippin, the jumping pony gelding with boundless energy and a heart of gold. Pippin's playful spirit and agility make him a natural in the jumping arena, clearing fences with ease. With his charming personality and steady temperament, Pippin is the perfect partner for young riders or those seeking a fun, reliable mount for jumping adventures. Don't miss out on the opportunity to soar to new heights with Pippin—contact us today!",
    "slideOne":"images/9.jpg",
    "slideTwo":"images/44.jpg",
    "slideThree":"images/45.jpg",
    "cryptoPrices":{
        Bitcoin:0.453074,
          Lightning:464.83000000,
            Ethereum:9.913488,
            USDC:30000,
            Tether:30000,
            LTC:363.8127,
            Doge:193548.387096
    }
},
{
    "id":10,
    "image":"images/25.jpg",
    "name" : "2019 Spectacular Chess M Gelding",
    "birth":"2019",
    "breed":"Chess M",
    "sex":"Gelding",
    "height" : "16hh",
    "dameSire":"Roasted Aus",
    "sire":"Zinnia",
    "price":"24000",
    "age":"Young Horses",
    "discipline":"Pleasure",
    "colour":"Black",
    "country":"Albania",
    "summary":"Chess M is a versatile and dependable gelding, ready for any riding adventure. With a calm demeanor and solid build, he's suitable for riders of all levels. Whether you're aiming for the arena or exploring the trails, Chess M is your perfect partner. Don't miss out on the opportunity to own this exceptional gelding. Contact us now to make Chess M a part of your equestrian journey!",
    "slideOne":"images/25.jpg",
    "slideTwo":"images/26.jpg",
    "slideThree":"images/27.jpg",
    "cryptoPrices":{
        Bitcoin:0.362726,
        Lightning:371.12000000,
        Ethereum:7.930449,
        USDC:24000,
        Tether:24000,
        LTC:290.909,
        Doge:154838.709677
    }
}, 
{
    "id":11,
    "image":"images/22.jpg",
    "name" : "2015 Children's Pony",
    "birth":"2015",
    "breed":"pony",
    "sex":"Mare",
    "height" : "13.2hh",
    "dameSire":"Caretino",
    "sire":"Cachas",
    "price":"11000",
    "age":"Adults",
    "colour":"Pinto",
    "country":"Albania",
    "discipline":"Pleasure",
    "summary":"Meet Pixie, the perfect children's pony with a heart of gold. Gentle, patient, and full of charm, Pixie is every child's dream companion. With a friendly demeanor and safe nature, Pixie brings joy and confidence to young riders. Whether it's pony rides or pony club adventures, Pixie is always ready for fun. Contact us today to make Pixie a beloved member of your family!",
    "slideOne":"images/22.jpg",
    "slideTwo":"images/23.jpg",
    "slideThree":"images/24.jpg",
    "cryptoPrices":{
        Bitcoin:0.16643,
        Lightning:170.10000000,
        Ethereum:3.635221,
        USDC:11000,
            Tether:11000,
            LTC:133.301,
            Doge:70967.741935
    }
},

{
    "id":12,
    "image":"images/28.jpg",
    "name" : "2020 Balou Du Rouet filly",
    "birth":"2020",
    "breed":"Filly",
    "sex":"Filly",
    "height" : "16.3hh",
    "dameSire":"Ixion Kwpn",
    "sire":"Ulft",
    "price":"13000",
    "age":"Foal",
    "colour":"Black",
    "country":"Albania",
    "discipline":"Pleasure",
    "summary":"Stella, a promising Balou Du Rouet filly, embodies elegance and athleticism. With impeccable bloodlines and graceful movement, Stella is destined for greatness in the show ring. Her sweet demeanor and curious spirit make her a joy to train and handle. Don't miss the chance to own this exceptional filly with a bright future. Contact us now to bring Stella into your equestrian world!",
    "slideOne":"images/28.jpg",
    "slideTwo":"images/29.jpg",
    "slideThree":"images/30.jpg",
    "cryptoPrices":{
        Bitcoin:0.19669,
        Lightning:201.02000000,
        Ethereum:4.299055,
        USDC:13000,
        Tether:13000,
        LTC:157.5757,
        Doge:84142.394822
    }
},
];

export default products;